gha

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -43,7 +43,6 @@ jobs:
       with:
         role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.AWS_ROLE_TO_ASSUME }}
         aws-region: ${{ env.AWS_DEFAULT_REGION }}
-        output-env-credentials: true
         role-duration-seconds: 900
         role-session-name: github-actions-session
   
@@ -58,12 +57,12 @@ jobs:
         
     - uses: actions/checkout@v4
     
-    - name: set up JDK 11
-      uses: actions/setup-java@v4
-      with:
-        java-version: '11'
-        distribution: 'zulu'
-        cache: gradle
+    # - name: set up JDK 11
+    #   uses: actions/setup-java@v4
+    #   with:
+    #     java-version: '11'
+    #     distribution: 'zulu'
+    #     cache: gradle
 
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
@@ -101,25 +100,38 @@ jobs:
     #   id: date # Give this step an ID
     #   run: echo "current_date_time=$(date +"%d-%m-%Y-%H-%I-%M-%S")" >> $GITHUB_ENV
 
+#----------------------------------------------------
+  # Job: Teardown Infrastructure
+  #----------------------------------------------------
   teardown:
     name: Teardown AWS Security Rules
     runs-on: ubuntu-latest
-    needs: [build]
-    if: always()
+    needs: [build] # Wait for the build job
+    if: always() # Run even if 'build' fails
 
     permissions:
       id-token: write # Required for OIDC role assumption
 
     steps:
+    # This job authenticates to AWS *independently*
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
+        role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.AWS_ROLE_TO_ASSUME }}
         aws-region: ${{ env.AWS_DEFAULT_REGION }}
-        use-existing-credentials: true
+        role-duration-seconds: 900 # Short-lived credentials
+        role-session-name: github-actions-teardown-session # Different session name
 
     - name: Remove GitHub Runner IP from Security Group
       run: |
+        # Get the IP from the 'build' job's outputs
         RUNNER_IP=${{ needs.build.outputs.runner_ip }}
+        
+        if [ -z "$RUNNER_IP" ]; then
+          echo "Error: Runner IP not found from build job outputs."
+          exit 1
+        fi
+        
         echo "Revoking ingress on port 9000 for IP: $RUNNER_IP"
         
         aws ec2 revoke-security-group-ingress \
